package com.example.visafind

import android.annotation.SuppressLint
import android.content.Intent
import android.os.Bundle
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class WelcomeActivity : AppCompatActivity() { // new class named "WelcomeActivity (autogenerated when creating a new "empyt activity" file
    @SuppressLint("MissingInflatedId")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_welcome)


        val mainButton: Button = findViewById(R.id.buttonScreen1)               // starting from "val main button" to "startActivity(intent)"
        val login: Button = findViewById(R.id.VAloginButton)               // starting from "val main button" to "startActivity(intent)"
        val register: Button = findViewById(R.id.registerButton)               // starting from "val main button" to "startActivity(intent)"
        //this block of code functions for the button in the first screen and
        mainButton.setOnClickListener {                                        // transitions to screen 2 (activity_main)
            val intent = Intent(this, MainActivity::class.java)
            startActivity(intent)
        }

        login.setOnClickListener {
            val intent = Intent(this, LoginActivity::class.java)           //  transitions to login screen (activity_login)
            startActivity(intent)
        }
        register.setOnClickListener {
            val intent = Intent(this, RegisterActivity::class.java)         // transitions to registration screen (activity_register)
            startActivity(intent)
        }
    }
}